version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: ai_writing_assistant_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - ai_writing_assistant_network

  backend:
    image: laura194/backend:latest
    container_name: ai_writing_assistant_backend
    depends_on:
      - mongodb
      - pandoc
    ports:
      - "5001:5001"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - tmp-data:/tmp                              
    networks:
      - ai_writing_assistant_network

  pandoc:
    image: laura194/pandoc:latest
    container_name: ai_writing_assistant_pandoc
    volumes:
      - tmp-data:/workspace                        
    working_dir: /workspace
    networks:
      - ai_writing_assistant_network
    entrypoint: ["sleep", "infinity"]              

  frontend:
    image: laura194/frontend:latest
    container_name: ai_writing_assistant_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - ai_writing_assistant_network

volumes:
  mongo-data:
  tmp-data:                                        

networks:
  ai_writing_assistant_network:
    driver: bridge
