version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: ai_writing_assistant_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - ai_writing_assistant_network

  backend:
    image: laura194/backend:latest
    container_name: ai_writing_assistant_backend
    depends_on:
      - mongodb
      - pandoc
    ports:
      - "5001:3000"   # Container lauscht auf 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # damit docker run geht
      - tmp-data:/tmp                              # tmpDir wird hier erzeugt
    networks:
      - ai_writing_assistant_network

  pandoc:
    image: laura194/pandoc:latest
    container_name: ai_writing_assistant_pandoc
    volumes:
      - tmp-data:/workspace                        # gleiche Daten wie /tmp im Backend
    working_dir: /workspace
    networks:
      - ai_writing_assistant_network
    entrypoint: ["sleep", "infinity"]              # bleibt wie bei dir

  frontend:
    image: laura194/frontend:latest
    container_name: ai_writing_assistant_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - ai_writing_assistant_network

volumes:
  mongo-data:
  tmp-data:                                        # gemeinsam genutztes Volume

networks:
  ai_writing_assistant_network:
    driver: bridge
