# Stage 1: Build
FROM node:22-alpine AS build

WORKDIR /app/backend

# package.json and package-lock.json copy and install
COPY backend/package*.json ./
RUN npm install

# Backend-Code kopieren
COPY backend ./

# TypeScript kompilieren
RUN npx tsc

# Stage 2: Runtime
FROM node:22-alpine

# Install Docker CLI
RUN apk add --no-cache docker-cli bash

WORKDIR /app/backend

COPY --from=build /app/backend/node_modules ./node_modules
COPY --from=build /app/backend/dist ./dist

# Build-time argument
ARG MONGO_URI
# Make the variable available at runtime
ENV MONGO_URI=${MONGO_URI}

EXPOSE 3000

CMD ["node", "dist/index.js"]
