# Stage 1: Build
FROM node:22-alpine AS build

WORKDIR /app/backend

# package.json und package-lock.json kopieren und installieren
COPY backend/package*.json ./
RUN npm install

# Backend-Code kopieren
COPY backend ./

# TypeScript kompilieren
RUN npx tsc

# Stage 2: Runtime
FROM node:22-alpine

# Docker CLI installieren, damit ExportService docker run ausführen kann
RUN apk add --no-cache docker-cli bash

WORKDIR /app/backend

COPY --from=build /app/backend/node_modules ./node_modules
COPY --from=build /app/backend/dist ./dist

# Argument zur Build-Zeit
ARG MONGO_URI
# Variable zur Runtime verfügbar machen
ENV MONGO_URI=$MONGO_URI

EXPOSE 3000

CMD ["node", "dist/index.js"]
