FROM node:22-alpine

WORKDIR /app

COPY backend/package*.json ./backend/

RUN cd backend && npm install

COPY backend ./backend

WORKDIR /app/backend

# .env wird zur Laufzeit übergeben, nicht ins Image kopieren!
EXPOSE 3000

CMD ["npm", "start"]
