name: CI

on:
  push:
    branches: [ "65-automatically-create-docker-image-of-application-and-upload-to-docker-hub" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Save version
        id: version
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          if [ "$VERSION" = "0.0.0" ] || [ -z "$VERSION" ]; then VERSION="latest"; fi
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build & Push Frontend
        run: |
          docker build . \
            --file docker-files/Dockerfile.frontend \
            --tag laura194/frontend:${{ steps.version.outputs.tag }} \
            --build-arg VITE_GOOGLE_API_KEY=${{ secrets.VITE_GOOGLE_API_KEY }} \
            --build-arg VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }} \
            --build-arg VITE_CLERK_SIGN_IN_FORCE_REDIRECT_URL=${{ secrets.VITE_CLERK_SIGN_IN_FORCE_REDIRECT_URL }} \
            --build-arg VITE_CLERK_SIGN_UP_FORCE_REDIRECT_URL=${{ secrets.VITE_CLERK_SIGN_UP_FORCE_REDIRECT_URL }} \
            --build-arg VITE_APP_EMAILJS_SERVICE_ID=${{ secrets.VITE_APP_EMAILJS_SERVICE_ID }} \
            --build-arg VITE_APP_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_APP_EMAILJS_TEMPLATE_ID }} \
            --build-arg VITE_APP_EMAILJS_PUBLIC_KEY=${{ secrets.VSSITE_APP_EMAILJS_PUBLIC_KEY }}
          docker push laura194/frontend:${{ steps.version.outputs.tag }}

      - name: Build & Push Backend
        run: |
          docker build . \
            --file docker-files/Dockerfile.backend \
            --tag laura194/backend:${{ steps.version.outputs.tag }} \
            --build-arg VITE_APP_EMAILJS_PUBLIC_KEY=${{ secrets.MONGO_URI }}
          docker push laura194/backend:${{ steps.version.outputs.tag }}
