name: Security Audit

on:
  schedule:
    - cron: '0 0 * * 1' # Läuft jeden Montag um Mitternacht

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Security Audit
        run: npm audit --audit-level=high
